"""empty message

Revision ID: f13c60481a43
Revises: 2b7380507a71
Create Date: 2022-04-22 01:53:04.371056

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f13c60481a43"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("password", sa.String(length=9999), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("createdAt", sa.TIMESTAMP(), nullable=True),
        sa.Column("lastLoginAt", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
